# Purpose: upload work in required format to Clarivate Web of Science Book Citation Index (BKCI).
# Uploads all active Thoth works with a publication date within the previous month.

# Credentials must be present as repository secrets named 
# BKCI_FTP_USER_[publisher_id] and BKCI_FTP_PW_[publisher_id]

# Content required: PDF work file
# Metadata required: CSV containing at minimum (1) titles provided, (2) ISBNs,
# (3) file name per title, (4) publication date
# Naming convention: Not strictly controlled, but use simple/human-readable names e.g. ISBN
# Upload directory: per-upload subfolder (e.g. datestamped) within `INCOMING-BOOKS` folder

name: bkci-bulk-disseminate

on:
  schedule:
    # 'at 06:40 on day-of-month 6'
    # There might be a delay between a book being published and the publisher
    # correctly setting its publication date and Active status in Thoth.
    # Therefore, this action is run a few days after the start of the month,
    # to minimise situations where e.g. a book which was published on the 31st, but
    # whose record was not updated until the 1st, is missed out of both months' runs.
    - cron: '40 6 6 * *'
  workflow_dispatch:

jobs:
  bkci-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'BKCI'
      env_publishers: ${{ vars.BKCI_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.BKCI_ENV_EXCEPTIONS }}
    secrets: inherit
