# Purpose: upload newly-published works from Thoth to Internet Archive.
# Uploads all active published Thoth works not yet found in Internet Archive.
# Work must have a valid URL supplied as the PDF Publication Canonical Location.
# IA credentials for a user with write permissions to the Thoth Archiving Network
# collection (e.g. thoth_pub) must be present as repository secrets
# named IA_S3_ACCESS (access key) and IA_S3_SECRET (secret key).
name: bulk-ia-upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      NEW_IDS: ${{ steps.get-ids.outputs.NEW_IDS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get list of work IDs using Python script
        id: get-ids
        # pip install command will be partially re-run when building Docker image in later step
        run: |
          pip install -r requirements_obtain_new_ids.txt
          output=$(python obtain_new_ids.py)
          echo "NEW_IDS=$output" >> $GITHUB_OUTPUT

  upload_to_ia:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(needs.build.outputs.NEW_IDS) }}
    steps:
      - name: Run disseminator using Dockerhub image
        uses: docker://openbookpublishers/thoth-dissemination:latest
        with:
          entrypoint: /disseminator.py
          ia_s3_access: ${{ secrets.IA_S3_ACCESS }}
          ia_s3_secret: ${{ secrets.IA_S3_SECRET }}
          args: >-
            --work ${{ matrix.work-id }}
            --platform InternetArchive