# Purpose: upload newly-published works from Thoth to Internet Archive.
# Uploads all active published Thoth works not yet found in Internet Archive.
# Work must have a valid URL supplied as the PDF Publication Canonical Location.
# IA credentials for a user with write permissions to the Thoth Archiving Network
# collection (e.g. thoth_pub) must be present as repository secrets
# named IA_S3_ACCESS (access key) and IA_S3_SECRET (secret key).
name: bulk-ia-upload

on:
  schedule:
    # 'at 00:15 on day-of-month 1'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '15 0 1 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    outputs:
      NEW_IDS: ${{ steps.get-ids.outputs.NEW_IDS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get list of work IDs using Python script
        id: get-ids
        run: |
          pip install -r requirements_obtain_new_ids.txt
          output=$(python obtain_new_ids.py)
          echo "NEW_IDS=$output" >> $GITHUB_OUTPUT
        env:
          ENV_PUBLISHERS: ${{ vars.ENV_PUBLISHERS }}
          ENV_EXCEPTIONS: ${{ vars.ENV_EXCEPTIONS }}

  bulk_ia_upload:
    needs: run-script
    uses: ./.github/workflows/ia_upload.yml
    with:
      work-ids: ${{ needs.run-script.outputs.NEW_IDS }}
    secrets: inherit