# Purpose: disseminate newly-published works from Thoth to the specified platform.
# Relevant credentials must be present as repository secrets.
name: bulk-disseminate

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      env_publishers:
        required: true
        type: string
      env_exceptions:
        required: true
        type: string

jobs:
  obtain-new-ids:
    runs-on: ubuntu-latest
    outputs:
      NEW_IDS: ${{ steps.get-ids.outputs.NEW_IDS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements_obtain_new_ids.txt

      - name: Get list of work IDs using Python script
        id: get-ids
        run: |
          output=$(python obtain_new_ids.py --platform ${{ inputs.platform }})
          echo "NEW_IDS=$output" >> $GITHUB_OUTPUT
        env:
          ENV_PUBLISHERS: ${{ inputs.env_publishers }}
          ENV_EXCEPTIONS: ${{ inputs.env_exceptions }}

  bulk-disseminate:
    needs: obtain-new-ids
    if: needs.obtain-new-ids.outputs.NEW_IDS != '[]'
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(needs.run-script.outputs.NEW_IDS) }}
    uses: ./.github/workflows/disseminate.yml
    with:
      work-id: ${{ matrix.work-id }}
      platform: ${{ inputs.platform }}
    secrets: inherit