# Purpose: deposit newly-updated works' metadata from Thoth to Crossref.
# Deposits all active/forthcoming Thoth works updated since last scheduled run.
# Crossref credentials for each relevant publisher must be present as repository secrets
# named CROSSREF_USER_[publisher_id] and CROSSREF_PW_[publisher_id].
name: cr-bulk-disseminate

on:
  schedule:
    # 'at 45 minutes past every hour'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '45 * * * *'
  workflow_dispatch:

jobs:
  cr-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'Crossref'
      env_publishers: ${{ vars.CR_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.CR_ENV_EXCEPTIONS }}
    secrets: inherit