# Logic shared between multiple workflows for disseminating one or more works
# (given as an array of work IDs) from Thoth to the specified platform.
name: disseminate

on:
  workflow_call:
    inputs:
      work-ids:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  disseminate:
    runs-on: ubuntu-latest
    outputs:
      OUTPUT: ${{ steps.docker_run.outputs.* }}
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Make all platform credentials available to later steps (with names lowercased)
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: lower
      - name: Run disseminator using Dockerhub image
        id: docker_run
        run: |
          docker run --rm \
          openbookpublishers/thoth-dissemination:test \
          ./disseminator.py \
          --work ${{ matrix.work-id }} \
          --platform ${{ inputs.platform }} \
          | echo "${{ matrix.work-id }}=$(cat)" >> $GITHUB_OUTPUT
      - name: Test passing output
        run: |
          echo "${{ steps.docker_run.outputs[matrix.work-id] }}"

  test-passing-output:
    runs-on: ubuntu-latest
    needs: disseminate
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Test passing output between jobs
        run: |
          echo "${{ needs.disseminate.outputs.OUTPUT }}"
    
