# Logic shared between multiple workflows for disseminating one or more works
# (given as an array of work IDs) from Thoth to the specified platform.
name: disseminate

on:
  workflow_call:
    inputs:
      work-id:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  disseminate:
    runs-on: ubuntu-latest
    permissions:
      # Required for Google Play workflow
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Make all platform credentials available to later steps (with names lowercased)
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: lower
          exclude: GOOGLE_WORKLOAD_ID_PROVIDER, GOOGLE_SERVICE_ACCOUNT

      - name: Checkout (google-github-actions/auth prerequisite)
        uses: actions/checkout@v4
        if: inputs.platform == 'GooglePlay'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        if: inputs.platform == 'GooglePlay'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Run disseminator using Dockerhub image
        run: |
          echo "DEBUG: Starting disseminator step"
          STDOUT="${{ inputs.work-id }}"
          STDERR=$(mktemp)
          HAS_ERRORS=false
          
          echo "DEBUG: About to run Python script"
          echo "DEBUG: STDOUT file: $STDOUT"
          echo "DEBUG: STDERR file: $STDERR"
          
          # Disable exit on error temporarily
          set +e
          python disseminator.py \
            --work "${{ inputs.work-id }}" \
            --platform "${{ inputs.platform }}" \
            > >(tee "$STDOUT") 2> >(tee "$STDERR" >&2)
          PYTHON_EXIT_CODE=$?
          set -e  # Re-enable exit on error
          
          echo "DEBUG: Python script completed with exit code: $PYTHON_EXIT_CODE"
          echo "DEBUG: Checking if STDERR file exists and has content"
          
          if [ -s "$STDERR" ]; then
            echo "DEBUG: STDERR file has content, processing errors"
            ERROR_LOG=$(grep '^ERROR:' "$STDERR" || true)
            echo "DEBUG: ERROR_LOG content: $ERROR_LOG"
            
            if [ -n "$ERROR_LOG" ]; then
              echo "DEBUG: Found error messages, writing to Job Summary"
              echo "### Dissemination error for work ID ${{ inputs.work-id }}" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              echo "$ERROR_LOG" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              HAS_ERRORS=true
              echo "DEBUG: Job Summary written, HAS_ERRORS set to true"
            else
              echo "DEBUG: No error messages found in stderr"
            fi
          else
            echo "DEBUG: STDERR file is empty or doesn't exist"
          fi
          
          echo "DEBUG: About to check HAS_ERRORS flag or Python exit code"
          # Exit after Job Summary has been written
          if [ "$HAS_ERRORS" = "true" ] || [ $PYTHON_EXIT_CODE -ne 0 ]; then
            echo "DEBUG: Errors found or Python script failed, sleeping then exiting"
            sleep 2
            exit 1
          else
            echo "DEBUG: No errors found, step should succeed"
          fi
          
          echo "DEBUG: Step completed successfully"

      - name: Upload output to artifact
        uses: actions/upload-artifact@v4
        if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
        with:
          name: ${{ inputs.work-id }}
          path: ${{ inputs.work-id }}
          retention-days: 7
          if-no-files-found: ignore
          overwrite: false

  write-locations:
    runs-on: ubuntu-latest
    needs: disseminate
    if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]'), inputs.platform)
    steps:
      - name: Checkout
        # This step deletes existing directory contents, so must be done before artifact download
        uses: actions/checkout@v4

      - name: Download disseminator output artifact containing location info
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.work-id }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements_write_locations.txt

      - name: Write locations to Thoth using Python script
        run: python write_locations.py ${{ inputs.work-id }}
        env:
          THOTH_EMAIL: ${{ secrets.THOTH_EMAIL }}
          THOTH_PWD: ${{ secrets.THOTH_PWD }}

  send-email:
    runs-on: ubuntu-latest
    needs: disseminate
    if: contains(fromJSON('["OAPEN", "EBSCOHost", "BKCI"]'), inputs.platform)
    steps:
      - name: Send notification email
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{ secrets.THOTH_SMTP }}
          subject: New book submitted to ${{ inputs.platform }} via Thoth (${{ inputs.work-id }})
          # NB: Actions secrets names are case-insensitive, so no need to check/change casing of platform name
          to: ${{ secrets[format('{0}_NOTIF_EMAIL', inputs.platform)] }}
          from: Thoth Open Metadata <distribution@thoth.pub>
          body: Please find the metadata submission for https://thoth.pub/books/${{ inputs.work-id }} in your upload folder. We look forward to receiving the file location once registered. Thank you!
          cc: info@thoth.pub
