# Logic shared between multiple workflows for disseminating one or more works
# (given as an array of work IDs) from Thoth to the specified platform.
name: disseminate

on:
  workflow_call:
    inputs:
      work-ids:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  disseminate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Make all platform credentials available to later steps (with names lowercased)
        uses: oNaiPs/secrets-to-env-action@v1.5
        with:
          secrets: ${{ toJSON(secrets) }}
          convert: lower
      - name: Run disseminator using Dockerhub image
        run: |
          docker run --rm \
          openbookpublishers/thoth-dissemination:test \
          ./disseminator.py \
          --work ${{ matrix.work-id }} \
          --platform ${{ inputs.platform }} \
          | echo "$(cat)" >> ${{ matrix.work-id }}
      - name: Check that output file works before uploading
        run: |
          cat ${{ matrix.work-id }}
      - name: Upload output to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.work-id }}
          path: ${{ matrix.work-id }}
          retention-days: 1
          if-no-files-found: ignore
          overwrite: false

  test-passing-output:
    runs-on: ubuntu-latest
    needs: disseminate
    if: contains(fromJSON('["InternetArchive", "CUL", "Figshare", "Zenodo"]')), inputs.platform
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Download output from artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.work-id }}
      - name: Test passing output between jobs using artifacts
        run: |
          cat ${{ matrix.work-id }}
