# Purpose: upload newly-published works from Thoth to (Loughborough) Figshare.
# Uploads all active Thoth works with a publication date in the previous month.
# Work must have a valid URL supplied for at least one Publication Canonical Location.
# Must also have a Long Abstract, a Licence, at least one Main Contribution
# and at least one Subject with type Keyword.
# Figshare credentials for a user with write permissions to the Thoth
# Archiving Network group (e.g. Thoth Archive Admin) must be present as a
# repository secret named FIGSHARE_TOKEN.
name: fs-bulk-disseminate

on:
  schedule:
    # 'at 00:15 on day-of-month 1'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '15 0 1 * *'
  workflow_dispatch:

jobs:
  fs-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'Figshare'
      env_publishers: ${{ vars.FS_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.FS_ENV_EXCEPTIONS }}
    secrets: inherit