# Purpose: upload newly-published works from Thoth to dedicated Google Play crawl server.
# Uploads all active Thoth works with a publication date within the previous day.
# Google Play collection-code for each relevant publisher must be present as
# repository secret named GOOGLE_PLAY_COLL_[publisher_id].
# Repository secrets GOOGLE_PLAY_BUCKET, GOOGLE_SERVICE_ACCOUNT and GOOGLE_WORKLOAD_ID_PROVIDER
# must also be present to allow connection to the crawl server.
name: gp-bulk-disseminate

on:
  schedule:
    # 'at 05:50 every day'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '50 5 * * *'
  workflow_dispatch:

jobs:
  gp-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'GooglePlay'
      env_publishers: ${{ vars.GP_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.GP_ENV_EXCEPTIONS }}
    secrets: inherit