# Purpose: upload newly-published works from Thoth to Internet Archive.
# Uploads all active published Thoth works not yet found in Internet Archive.
# Work must have a valid URL supplied as the PDF Publication Canonical Location.
# IA credentials for a user with write permissions to the Thoth Archiving Network
# collection (e.g. thoth_pub) must be present as repository secrets
# named IA_S3_ACCESS (access key) and IA_S3_SECRET (secret key).
name: ia-bulk-disseminate

on:
  schedule:
    # 'at 00:15 on day-of-month 1'
    # (scheduling is not guaranteed; runs at the start of the hour
    # are more likely to be delayed)
    - cron: '15 0 1 * *'
  workflow_dispatch:

jobs:
  ia-bulk-disseminate:
    uses: ./.github/workflows/bulk_disseminate.yml
    with:
      platform: 'InternetArchive'
      env_publishers: ${{ vars.IA_ENV_PUBLISHERS }}
      env_exceptions: ${{ vars.IA_ENV_EXCEPTIONS }}
    secrets: inherit