# Logic shared between multiple workflows for uploading one or more works
# (given as an array of work IDs) from Thoth to Internet Archive.
# Work must have a valid URL supplied as the PDF Publication Canonical Location.
# Work must not have previously been uploaded to Internet Archive.
# IA credentials for a user with write permissions to the Thoth Archiving Network
# collection (e.g. thoth_pub) must be present as repository secrets
# named IA_S3_ACCESS (access key) and IA_S3_SECRET (secret key).
name: ia-upload

on:
  workflow_call:
    inputs:
      work-ids:
        required: true
        type: string

jobs:
  upload_to_ia:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Run disseminator using Dockerhub image
        uses: docker://openbookpublishers/thoth-dissemination:latest
        with:
          entrypoint: /disseminator.py
          args: >-
            --work ${{ matrix.work-id }}
            --platform InternetArchive
        env:
          ia_s3_access: ${{ secrets.IA_S3_ACCESS }}
          ia_s3_secret: ${{ secrets.IA_S3_SECRET }}