# Logic shared between multiple workflows for disseminating one or more works
# (given as an array of work IDs) from Thoth to the specified platform.
name: disseminate

on:
  workflow_call:
    inputs:
      work-ids:
        required: true
        type: string
      platform:
        required: true
        type: string

jobs:
  disseminate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work-id: ${{ fromJSON(inputs.work-ids) }}
    steps:
      - name: Run disseminator using Dockerhub image
        uses: docker://openbookpublishers/thoth-dissemination:latest
        with:
          entrypoint: /disseminator.py
          args: >-
            --work ${{ matrix.work-id }}
            --platform ${{ inputs.platform }}
        env:
          # TODO also include Crossref secrets (perhaps branching on platform)
          ia_s3_access: ${{ secrets.IA_S3_ACCESS }}
          ia_s3_secret: ${{ secrets.IA_S3_SECRET }}