name: test-workflow

on:
  workflow_dispatch:
    inputs:
      workId:
        description: 'Thoth work ID'
        required: true

env:
  TEST_TAG: test

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Do something simple
        run: |
          echo "Work ID: ${{ github.event.inputs.workId }}"
          echo "Test secret: ${{ secrets.TEST_SECRET }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ env.TEST_TAG }}

      - name: Run disseminator using Docker image
        run: |
          docker run \
            --env ia_s3_access=${{ secrets.TEST_SECRET }} \
            --env ia_s3_secret=${{ secrets.TEST_SECRET }} \
            --rm ${{ env.TEST_TAG }} \
            ./disseminator.py --work ${{ github.event.inputs.workId }} \
            --platform InternetArchive